# Generated by Django 4.2.26 on 2025-11-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_inquiry_latitude_inquiry_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
