# Generated by Django 4.2.26 on 2025-11-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_inquiry_guest_id_alter_inquiry_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True),
        ),
    ]
