# Generated by Django 4.2.26 on 2025-11-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_branch_email_adress_branch_closing_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='primery_branch',
            field=models.BooleanField(default=False),
        ),
    ]
