# Generated by Django 4.2 on 2025-11-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_branch_primery_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(default='قيد المعالجة', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='place_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='show_quantity',
            field=models.BooleanField(default=True),
        ),
    ]
