# Generated by Django 4.2 on 2025-12-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
