# Generated by Django 4.2 on 2025-12-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
