# Generated by Django 4.2 on 2025-12-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_invoiceitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
