# Generated by Django 4.2 on 2025-12-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_invoice_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default-slug', editable=False, max_length=255, unique=True),
        ),
    ]
