# Generated by Django 5.1.7 on 2025-12-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_invoiceitem_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit before discount', max_digits=10, null=True),
        ),
    ]
