# Generated by Django 4.2 on 2025-12-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_invoiceitem_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
