# Generated by Django 4.2 on 2026-01-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_banner_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.JSONField(blank=True, default=list, help_text="Available colors, e.g., ['Red', 'Blue', 'Green']"),
        ),
    ]
