# Generated by Django 4.2 on 2026-01-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('completed', 'مكتملة'), ('canceled', 'ملغاة'), ('refunded', 'مسترجعة')], default='pending', max_length=20),
        ),
    ]
