# Generated by Django 4.2 on 2026-01-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='main.product'),
        ),
    ]
