# Generated by Django 4.2 on 2026-01-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delveried_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
