# Generated by Django 4.2 on 2026-01-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_contactmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
