# Generated by Django 4.2 on 2026-01-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_invoiceitem_color_invoiceitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
