# Generated by Django 4.2 on 2026-01-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_cashregister_cashtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtransaction',
            name='cash_register',
        ),
        migrations.DeleteModel(
            name='CashRegister',
        ),
        migrations.DeleteModel(
            name='CashTransaction',
        ),
    ]
